apiVersion: v1
kind: ConfigMap
metadata:
  name: career-tracker-config
  namespace: {{ .Release.Namespace }}
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Moodle__BaseUrl: "http://moodle-service.career-tracker.svc.cluster.local/Mymoodle/webservice/rest/server.php"